format = """
[ ](bg:#585858)\
$os\
$battery(bg:#CCCC11 fg:#1111CC)\
$username\
(bg:#444444 fg:#585858)\
$hostname\
(bg:#0087AF fg:#444444)\
$directory\
$conda\
(fg:#0087AF) \
$fill\
$git_branch\
$git_status\
$git_commi\
$nodejs\
$rust\
$localip
$character
"""


# Disable the blank line at the start of the prompt
add_newline = true

[battery]
full_symbol='󰁹'
empty_symbol=''
charging_symbol='󰂄'
discharging_symbol='󰂀'
unknown_symbol='󰂑'
format = '[$symbol$percentage](red) '

[conda]
symbol = "󰬌 "


[character]
success_symbol = '[────>](bold green) '
error_symbol = '[✗](bold red) '


[linebreak]
disable = true


# You can also replace your username with a neat symbol like  or disable this
# and use the os module below
[username]
show_always = true
style_root = "bg:#585858"
format = '[$user ]($style)'
disabled = false




# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#585858"
disabled = true # Disabled by default


[fill]
symbol = " "

[hostname]
ssh_only = true
ssh_symbol = ''
format = '[$ssh_symbol]($style)[ on ]($style)[$hostname](fg:red)'


[directory]
style = "fg:#303030"
read_only = ''
read_only_style="fg:#AF0000"
format = '[ $path ]($style)[$read_only]($read_only_style)'
truncation_length = 5
truncation_symbol = ":"
truncate_to_repo = true
home_symbol = '󰋜'
use_os_path_sep = false


# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "


[git_status]
up_to_date = " "
conflicted = " "
untracked = "？"
stashed = " "
modified = " "
staged = " "
renamed = " "
deleted = "✘ "
style = "bold yellow"
ahead = "▲ ${count}"
behind = "▼ ${count}"
diverged = "▲ ${ahead_count} ▼ ${behind_count}"
format = "[|](fg:base bg:none)[$all_status$ahead_behind](fg:$style bg:base)[|](fg:base bg:none) "


[git_commit]
tag_symbol = " "
format = "[|](fg:base bg:none)[($hash$tag)](fg:$style bg:base)[|](fg:base bg:none) "


[git_branch]
style = "bold underline purple"
format = "[|](fg:base bg:none)[$symbol$branch(:$remote_branch)](fg:$style bg:base)[|](fg:base bg:none) "


[cmd_duration]
style = "white"
format = "[|](fg:base bg:none)[ $duration](fg:$style bg:base)[|](fg:base bg:none) "


[c]
style = "bold green"
symbol = " "
format = "[|](fg:base bg:none)[$symbol($version(-$name))](fg:$style bg:base)[|](fg:base bg:none) "


[java]
style = "bold green"
symbol = " "
format = "[|](fg:base bg:none)[${symbol}(${version})](fg:$style bg:base)[|](fg:base bg:none) "


[golang]
style = "bold green"
symbol = "GO "
format = "[|](fg:base bg:none)[$symbol($version)](fg:$style bg:base)[|](fg:base bg:none) "


[python]
style = "bold cyan"
symbol = " "
format = "[|](fg:base bg:none)[${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\) )](fg:$style bg:base)[|](fg:base bg:none) "


[rust]
style = "bold red"
symbol = "󰬙 "
format = "[|](fg:base bg:none)[$symbol($version)](fg:$style bg:base)[|](fg:base bg:none) "


[zig]
style = "bold green"
symbol = " "
format = "[|](fg:base bg:none)[$symbol($version)](fg:$style bg:base)[|](fg:base bg:none) "

